USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS
SELECT 
    d.state,
    SUM(f.sales_price) AS total_sales
FROM SILVER.FACT_SALES f
JOIN SILVER.CUSTOMER_DIM d
    ON f.customer_sk = d.customer_sk
GROUP BY d.state;


CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS
SELECT 
  YEAR(TRANSACTION_DATE) AS SALES_YEAR,
  SUM(SALES_PRICE) AS TOTAL_SALES
  FROM SILVER.FACT_SALES
  GROUP BY SALES_YEAR;
  

  --SALES BY STORE EVERY MONTH
  CREATE OR REPLACE table GOLD.MONTHLY_SALES AS
  SELECT 
     DATE_TRUNC('MONTH',TRANSACTION_DATE) AS SALES_MONTH,
     SUM(SALES_PRICE) AS TOTAL_SALES
     FROM SILVER.FACT_SALES
     GROUP BY SALES_MONTH;

--TOP 10 STORES BY SALES
CREATE OR REPLACE TABLE GOLD.TOP_STORES AS
 SELECT 
     STORE_ID,
     SUM(SALES_PRICE)AS TOTAL_SALES
     FROM SILVER.FACT_SALES
     GROUP BY STORE_ID
     ORDER BY TOTAL_SALES DESC 
     LIMIT 10;

 SELECT COUNT(*) FROM GOLD.SALES_BY_STATE;
 SELECT COUNT(*) FROM GOLD.SALES_BY_YEAR;
SELECT COUNT(*) FROM GOLD.MONTHLY_SALES;
SELECT * FROM GOLD.TOP_STORES;

--PERFORMANCE VALIDATION
SELECT SUM(SALES_PRICE) FROM SILVER.FACT_SALES;
SELECT SUM(TOTAL_SALES) FROM GOLD.SALES_BY_YEAR;
SELECT SUM(TOTAL_SALES) FROM GOLD.SALES_BY_STATE;


